# NUMPY

### EX. 1

Create a numpy array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
       
and square each member.

In [2]:
import numpy as np
np.square(np.arange(100))

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

### EX. 2

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Suppose you wan to select xarr values according to cond, otherwise by yarr.
Use np.where to select the following values from xarr and yarr

In [24]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) 
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) 
cond = np.array([True, False, True, True, False])

In [25]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

### EX. 3

array([[-1.08564153, -0.72716847,  0.74606065, -1.40633312],
       [-1.86039438, -0.28634009, -0.09945923, -1.12303756],
       [ 0.52477458,  0.7553261 , -0.03897405, -2.08005753],
       [-1.19438104, -0.09444864, -0.56611071, -0.74047666]])
Use np.where to replace values that are lower than 1 to 5, otherwise to 20

In [44]:
box = np.array([[-1.08564153, -0.72716847,  0.74606065, -1.40633312],
       [-1.86039438, -0.28634009, -0.09945923, -1.12303756],
       [ 0.52477458,  0.7553261 , -0.03897405, -2.08005753],
       [-1.19438104, -0.09444864, 2.56611071, -0.74047666]])

In [45]:
np.where(box < 1 , 5, box)

array([[5.        , 5.        , 5.        , 5.        ],
       [5.        , 5.        , 5.        , 5.        ],
       [5.        , 5.        , 5.        , 5.        ],
       [5.        , 5.        , 2.56611071, 5.        ]])

In [42]:
box<1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### EX. 4

1. Calculate the mean of the follwing np.array arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
2. Calculate the mean according to columns

### EX. 5

np.array([-10, 1, -5, 3, 4, -5, 6, 7])

select only the positive values and sum them together.

In [28]:
(box > 0).sum()

5

In [30]:
(box > 0).sum()

5

In [31]:
 (box > 0)

array([False,  True, False,  True,  True, False,  True,  True])

In [34]:
box[ (box > 0)].sum()

21

In [26]:
import numpy as np
box = np.array([-10, 1, -5, 3, 4, -5, 6, 7])

In [7]:
box2 = np.where(box > 0)

In [9]:
np.square(box2)

array([[ 1,  9, 16, 36, 49]])

### EX. 6

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

Index the array to select only the Joe 

### EX.7

In [ ]:
create the following array
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

and select numbers in the follwing order :
    array([ 2, 24, 26, 5])

### EX. 8

In [ ]:
array([[ 1,  8,  9, 16],
       [ 5,  1,  1,  3],
       [19, 20,  4,  6]])
1. sort according first axis
2. sor according to second axis

In [47]:
box = np.array([[ 1,  8,  9, 16],
       [ 5,  1,  1,  3],
       [19, 20,  4,  6]])

In [49]:
box.sort(axis=0)
box

array([[ 1,  1,  1,  3],
       [ 5,  8,  4,  6],
       [19, 20,  9, 16]])

In [54]:
box = np.array([[ 1,  8,  9, 16],
                [ 5,  1,  1,  3],
                [19, 20,  4,  6]])
box.sort(axis=0)
box

array([[ 1,  1,  1,  3],
       [ 5,  8,  4,  6],
       [19, 20,  9, 16]])

array([[ 1,  1,  1,  3],
       [ 5,  8,  4,  6],
       [19, 20,  9, 16]])

### EX. 9

Find unique values np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [52]:
box = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(box)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

### EX. 10

Test if the following values exist in the array [1,4,5] np.array([6, 0, 0, 3, 2, 5, 6])