# NumPy Basics: Arrays and Vectorized Computation

To give you an idea of the performance difference, consider a NumPy array of one million integers, and the equivalent Python list

In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 18.7 ms, sys: 13 ms, total: 31.7 ms
Wall time: 30.1 ms
CPU times: user 444 ms, sys: 56.6 ms, total: 501 ms
Wall time: 502 ms


NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

## The NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.
To give you a flavor of how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects, I first import NumPy and generate a small array of random data

In [7]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 1.12208594, -0.26858869,  0.70753007],
       [ 1.3059848 ,  0.00821777,  0.11780816]])

I then write mathematical operations with data:


In [11]:
data * 10

array([[11.22085941, -2.68588695,  7.07530069],
       [13.05984802,  0.08217773,  1.17808159]])

In [12]:
data + data

array([[ 2.24417188, -0.53717739,  1.41506014],
       [ 2.6119696 ,  0.01643555,  0.23561632]])

In the first example, all of the elements have been multiplied by 10. In the second, the corresponding values in each “cell” in the array have been added to each other.

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array:

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

### Creating ndarrays

The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good candidate for conversion

In [15]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array

In [21]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape inferred from the data. We can confirm this by inspecting the ndim and shape attributes

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

Unless explicitly specified (more on this later), np.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype metadata object; for example, in the previous two examples we have:

In [24]:
arr1.dtype
arr2.dtype

dtype('int64')

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape. empty creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
# Return a new array of given shape and type, with random values
np.empty((2, 3, 2))

array([[[0.60692535, 2.66294077],
        [1.39882417, 1.08826551],
        [0.03381007, 1.49385735]],

       [[1.2435198 , 0.89147332],
        [1.76533586, 0.27623747],
        [1.29063066, 0.97166482]]])

In [48]:
np.empty((2,3,4))

array([[[ 0.00000000e+000,  0.00000000e+000,  6.91691904e-323,
          0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          2.14321575e-312],
        [ 0.00000000e+000, -1.29073617e-231,  2.96439388e-323,
         -1.29073617e-231],
        [ 1.16442250e-028,  2.15181698e+160,  0.00000000e+000,
         -1.29073617e-231]]])

arange is an array-valued version of the built-in Python range function

In [49]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data

In [50]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:

In [51]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
float_arr.dtype

int64


dtype('float64')

In [53]:
float_arr

array([1., 2., 3., 4., 5.])

In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated

In [54]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form

In [55]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:


In [57]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in
the array

In [59]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [60]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays

In [61]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [62]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

### Basic Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]
arr[5:8]

array([5, 6, 7])

In [49]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [69]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

Now, when I change values in arr_slice, the mutations are reflected in the original array arr

In [52]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The “bare” slice [:] will assign to all values in an array

In [58]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr_slice

array([64, 64, 64])

In [55]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays

In [70]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[0]

array([1, 2, 3])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-separated list of indices to select individual elements. So these are equivalent

In [62]:
arr2d[0][2]
arr2d[0, 2]

3

In [68]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d.shape

(3, 3)

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d:

In [78]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d.ndim

3

In [88]:
arr3d[1][0][2]

9

In [59]:
arr3d.shape

(2, 2, 3)

Both scalar values and arrays can be assigned to arr3d[0]

In [77]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0),
forming a 1-dimensional array

In [79]:
arr3d[1, 0]

array([7, 8, 9])

This expression is the same as though we had indexed in two steps

In [80]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### Indexing with slices

Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax

In [89]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr
arr[1:6]

array([1, 2, 3, 4, 5])

Consider the two-dimensional array from before, arr2d. Slicing this array is a bit different

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

As you can see, it has sliced along axis 0, the first axis. A slice, therefore, selects a range of elements along an axis. It can be helpful to read the expression arr2d[:2] as “select the first two rows of arr2d.”
You can pass multiple slices just like you can pass multiple indexes

In [96]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

When slicing like this, you always obtain array views of the same number of dimen‐
sions. By mixing integer indexes and slices, you get lower dimensional slices. For example, I can select the second row but only the first two columns like so

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr2d[1, :2]

array([4, 5])

Similarly, I can select the third column but only the first two rows like so

In [83]:
arr2d[:2, 2]

array([3, 6])

Note that a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing

In [99]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

Of course, assigning to a slice expression assigns to the whole selection

In [68]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

![f](figures/figuresWes/numpy1.png)

![f](figures/figuresWes/numpy2.png)

### Boolean Indexing

Let’s consider an example where we have some data in an array and an array of names with duplicates. I’m going to use here the randn function in numpy.random to generate some random normally distributed data

In [100]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 0.42127803, -0.0770104 , -1.59206858, -0.31721603],
       [-2.74776322, -1.22890666, -0.47379244, -0.48946764],
       [-0.33265253,  1.38461854, -0.86156411,  0.27908423],
       [ 1.38149228,  1.03880321, -0.5362147 ,  0.24353422],
       [-0.89148491,  1.90645875, -0.70508303, -0.35358239],
       [ 0.02111773,  0.01345717,  1.24288322, -0.767855  ],
       [ 0.25980734,  0.26036114,  0.45921036, -0.41912194]])

In [103]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

Suppose each name corresponds to a row in the data array and we wanted to select all the rows with corresponding name 'Bob'. Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with the string 'Bob' yields a boolean array

In [105]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the array

In [106]:
data[names == 'Bob']

array([[ 0.42127803, -0.0770104 , -1.59206858, -0.31721603],
       [ 1.38149228,  1.03880321, -0.5362147 ,  0.24353422]])

The boolean array must be of the same length as the array axis it’s indexing. You can even mix and match boolean arrays with slices or integers (or sequences of integers; more on this later).
In these examples, I select from the rows where names == 'Bob' and index the columns, too

In [107]:
data[names == 'Bob', 2:]

array([[-1.59206858, -0.31721603],
       [-0.5362147 ,  0.24353422]])

In [108]:
data[names == 'Bob', 3]

array([-0.31721603,  0.24353422])

To select everything but 'Bob', you can either use != or negate the condition using ~:
The ~ operator can be useful when you want to invert a general condition

In [109]:
names != 'Bob'
data[~(names == 'Bob')]

array([[-2.74776322, -1.22890666, -0.47379244, -0.48946764],
       [-0.33265253,  1.38461854, -0.86156411,  0.27908423],
       [-0.89148491,  1.90645875, -0.70508303, -0.35358239],
       [ 0.02111773,  0.01345717,  1.24288322, -0.767855  ],
       [ 0.25980734,  0.26036114,  0.45921036, -0.41912194]])

The ~ operator can be useful when you want to invert a general condition:

In [107]:
cond = names == 'Bob'
data[~cond]

array([[ 0.78195919, -0.76222849, -0.28883125, -0.61821405],
       [ 1.15987732, -1.17911112,  0.65514935, -0.76411448],
       [-1.3723042 , -0.21383503, -2.07472709, -1.66741931],
       [-0.71245793, -0.6780871 ,  0.46245494, -1.13936959],
       [ 0.0414589 , -2.32542242, -0.66649417,  0.03729418]])

Selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operators like & (and) and | (or):


In [111]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[ 0.42127803, -0.0770104 , -1.59206858, -0.31721603],
       [-0.33265253,  1.38461854, -0.86156411,  0.27908423],
       [ 1.38149228,  1.03880321, -0.5362147 ,  0.24353422],
       [-0.89148491,  1.90645875, -0.70508303, -0.35358239]])

In [112]:
data < 0

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.Setting values with boolean arrays works in a common-sense way. To set all of the negative values in data to 0 we need only do:

In [113]:
data[data < 0] = 0
data

array([[0.42127803, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.38461854, 0.        , 0.27908423],
       [1.38149228, 1.03880321, 0.        , 0.24353422],
       [0.        , 1.90645875, 0.        , 0.        ],
       [0.02111773, 0.01345717, 1.24288322, 0.        ],
       [0.25980734, 0.26036114, 0.45921036, 0.        ]])

Setting whole rows or columns using a one-dimensional boolean array is also easy

In [113]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.78195919, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.46245494, 0.        ],
       [0.0414589 , 0.        , 0.        , 0.03729418]])

### Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had an 8 × 4 array

In [114]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order

In [115]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Hopefully this code did what you expected! Using negative indices selects rows from the end

In [73]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a one-
dimensional array of elements corresponding to each tuple of indices

In [122]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [124]:
arr[[0,1], [1,2]]

array([1, 6])

In [115]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected. Regardless of how many dimensions the array has (here, only 2), the result of fancy indexing is always one-dimensional.
The behavior of fancy indexing in this case is a bit different from what some users might have expected (myself included), which is the rectangular region formed by selecting a subset of the matrix’s rows and columns. Here is one way to get that

In [117]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and also the special T attribute

In [113]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [121]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

When doing matrix computations, you may do this very often—for example, when computing the inner matrix product using np.dot

In [114]:
arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

array([[ 4.87350434,  0.34171714, -0.53904212],
       [ 0.34171714,  2.48909698, -2.50173734],
       [-0.53904212, -2.50173734,  9.57437168]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐ mute the axes (for extra mind bending)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

Here, the axes have been reordered with the second axis first, the first axis second, and the last axis unchanged.
Simple transposing with .T is a special case of swapping axes. ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to reararange the data

In [ ]:
arr
arr.swapaxes(1, 2)