# NUMPY

### EX. 1

Create a numpy array with float type for the list [1, 2, 3]

In [1]:
import numpy as np
np.array([1,2,3,]).astype(float)

array([1., 2., 3.])

### EX. 2

Create an numpy array that converts words into numbers. ['1.25', '-9.6', '42']

In [7]:
box = np.array(["2.4", '33']).astype(float)

In [8]:
box.dtype

dtype('float64')

### EX. 3

Subtract the follwing arrays np.array([[1., 2., 3.], [4., 5., 6.]]) np.array([[5., 5., 3.], [4., 5., 6.]])

In [9]:
box =   np.array([[1., 2., 3.], [4., 5., 6.]]) 
box_2= np.array([[5., 5., 3.], [4., 5., 6.]])
box - box_2

array([[-4., -3.,  0.],
       [ 0.,  0.,  0.]])

### EX. 4

Arange the values in numpy array from 1 to 10 and change the third value into 5000

In [16]:
box = np.arange(0,11)
box

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
box[3] = 5000

In [19]:
box

array([   0,    1,    2, 5000,    4,    5,    6,    7,    8,    9,   10])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### EX. 5

Slice the following array 
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
       
into this 
array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
box = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
       

In [10]:
box[:2]

array([[1, 2, 3],
       [4, 5, 6]])

### EX. 6

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

Index the array to select only the Joe 

In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [19]:
data

array([[ 0.863919  ,  1.65396017,  0.66780692, -3.46498964],
       [ 0.65703987, -1.74071907,  0.93447294, -1.95130312],
       [ 0.08536478,  1.46201114, -0.56701119,  0.51058422],
       [ 0.77785458,  0.64697564,  1.09770607, -0.3171106 ],
       [-0.6815341 , -0.69323002,  0.69111866, -0.19094149],
       [ 2.21298091,  0.15711587,  0.77807107,  0.68117815],
       [ 0.44047767,  1.23775695,  0.86892516, -0.53097904]])

In [15]:
data[names == 'Joe']

array([[ 0.65703987, -1.74071907,  0.93447294, -1.95130312],
       [ 2.21298091,  0.15711587,  0.77807107,  0.68117815],
       [ 0.44047767,  1.23775695,  0.86892516, -0.53097904]])

### EX.7

create the following array
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

and select numbers in the follwing order :
    array([ 2, 24, 26, 5])

In [21]:
box = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23], [24, 25, 26, 27], [28, 29, 30, 31]])

In [22]:
box

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
box[[0,6, 6,1],[2,0,2,1]]

array([ 2, 24, 26,  5])